export interface Product {
  id: string;
  name: string;
  category: 'earrings' | 'keychains' | 'bracelets' | 'necklaces';
  price: number;
  originalPrice?: number;
  image: string;
  images?: string[];
  description: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  badge?: 'new' | 'sale' | 'trending';
  colors?: string[];
  material?: string;
  dimensions?: string;
  care?: string;
}

const SUPABASE_IMG = 'https://uqradmprupflbivhzshi.supabase.co/storage/v1/object/public/products';

export const products: Product[] = [
  {
    id: 'ear-001',
    name: 'Lavender Dream Butterfly Earrings',
    category: 'earrings',
    price: 4067,
    image: `${SUPABASE_IMG}/earrings-purple-butterfly-star.jpg`,
    description: 'Delicate lavender butterfly charm earrings with opal-inspired resin details.',
    rating: 4.9,
    reviewCount: 178,
    inStock: true,
    badge: 'trending',
    material: 'Surgical steel with resin',
    colors: ['Lavender'],
    care: 'Avoid water and perfume',
  },
  {
    id: 'ear-002',
    name: 'Golden Butterfly Earrings',
    category: 'earrings',
    price: 4067,
    image: `${SUPABASE_IMG}/earrings-yellow-butterfly-star.jpg`,
    description: 'Classic gold-toned butterfly earrings with pearl accents.',
    rating: 4.9,
    reviewCount: 203,
    inStock: true,
    material: 'Gold-plated brass with pearl',
    colors: ['Gold'],
    care: 'Wipe clean with soft cloth',
  },
  {
    id: 'ear-003',
    name: 'Blue Butterfly Drop Earrings',
    category: 'earrings',
    price: 4067,
    originalPrice: 8217,
    image: `${SUPABASE_IMG}/earrings-blue-butterfly-star.jpg`,
    description: 'Charming blue butterfly earrings with star accents.',
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    badge: 'sale',
    material: 'Surgical steel with resin',
    colors: ['Blue'],
    care: 'Keep dry',
  },
  {
    id: 'ear-004',
    name: 'Rainbow Heart Pendant Earrings',
    category: 'earrings',
    price: 4067,
    image: `${SUPABASE_IMG}/necklace-galaxy-heart-pair.jpg`,
    description: 'Multicolor gradient heart earrings on delicate black cord.',
    rating: 4.7,
    reviewCount: 124,
    inStock: true,
    material: 'Acrylic with black cord',
    colors: ['Rainbow Gradient'],
    care: 'Avoid direct sunlight',
  },
  {
    id: 'ear-005',
    name: 'Cherry Red Heart Earrings',
    category: 'earrings',
    price: 4067,
    image: `${SUPABASE_IMG}/necklace-red-heart-trio.jpg`,
    description: 'Bold cherry red heart earrings on black string.',
    rating: 4.6,
    reviewCount: 98,
    inStock: true,
    material: 'Acrylic hearts with black string',
    colors: ['Cherry Red'],
    care: 'Handle with care',
  },
  {
    id: 'key-001',
    name: 'Mystical Bow Charm Keychain',
    category: 'keychains',
    price: 9047,
    image: `${SUPABASE_IMG}/phone-charm-pink-flower-bow.jpg`,
    description: 'Elegant bow with dangling mystical charm elements.',
    rating: 4.9,
    reviewCount: 287,
    inStock: true,
    badge: 'trending',
    material: 'Silver-toned metal with acrylic',
    colors: ['Silver'],
    care: 'Wipe with dry cloth',
  },
  {
    id: 'key-002',
    name: 'Racing Blue Keychain',
    category: 'keychains',
    price: 8217,
    image: `${SUPABASE_IMG}/keychain-williams-f1-blue.jpg`,
    description: 'Sporty racing car charm with blue and white detailing.',
    rating: 4.5,
    reviewCount: 92,
    inStock: true,
    material: 'Metal with enamel coating',
    colors: ['Blue & White'],
    care: 'Keep dry',
  },
  {
    id: 'key-003',
    name: 'Crystal Flower Cascade Keychain',
    category: 'keychains',
    price: 9047,
    image: `${SUPABASE_IMG}/phone-charm-blue-flower.jpg`,
    description: 'Multi-strand beaded keychain with crystal flowers and pearls.',
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    material: 'Beads, pearls, and metal chains',
    colors: ['Multi-pastel'],
    care: 'Avoid harsh pulling',
  },
  {
    id: 'key-004',
    name: 'Black Star Charm Keychain',
    category: 'keychains',
    price: 9877,
    image: `${SUPABASE_IMG}/phone-charm-black-bow-star.jpg`,
    description: 'Minimalist black beads with star and charm accents.',
    rating: 4.7,
    reviewCount: 113,
    inStock: true,
    material: 'Black beads with silver charms',
    colors: ['Black & Silver'],
    care: 'Keep away from moisture',
  },
  {
    id: 'key-005',
    name: 'Pastel Dream Lanyard Keychain',
    category: 'keychains',
    price: 9047,
    originalPrice: 13197,
    image: `${SUPABASE_IMG}/phone-charm-pink-purple-strap.jpg`,
    description: 'Soft pastel beads with decorative charms on purple cord.',
    rating: 4.8,
    reviewCount: 134,
    inStock: true,
    badge: 'sale',
    material: 'Beads on purple cord',
    colors: ['Pastel Mix'],
    care: 'Wipe gently',
  },
  {
    id: 'key-006',
    name: 'Gaming Lover Keychain',
    category: 'keychains',
    price: 9877,
    image: `${SUPABASE_IMG}/keychain-guitar-phone-charm.jpg`,
    description: 'Fun music and gaming-themed charms with dice and hearts.',
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
    material: 'Metal charms with beads',
    colors: ['Multi'],
    care: 'Dust occasionally',
  },
  {
    id: 'key-007',
    name: 'Green Bow Vine Keychain',
    category: 'keychains',
    price: 9047,
    image: `${SUPABASE_IMG}/phone-charm-green-bow-double.jpg`,
    description: 'Nature-inspired green bow with vine and charm details.',
    rating: 4.8,
    reviewCount: 167,
    inStock: true,
    badge: 'new',
    material: 'Metal with enamel and beads',
    colors: ['Green'],
    care: 'Avoid extreme heat',
  },
  {
    id: 'key-008',
    name: 'Minimalist Pearl Keychain',
    category: 'keychains',
    price: 9877,
    image: `${SUPABASE_IMG}/keychain-maliha-personalized.jpg`,
    description: 'Personalized name keychain with pearl and charm beads.',
    rating: 4.7,
    reviewCount: 112,
    inStock: true,
    material: 'Pearls with silver-tone metal',
    colors: ['Pearl White'],
    care: 'Keep dry',
  },
  {
    id: 'key-009',
    name: 'Mystical Bow Star Keychain',
    category: 'keychains',
    price: 10707,
    image: `${SUPABASE_IMG}/phone-charm-green-bow-star.jpg`,
    description: 'Elegant bow with star and pearl charm ensemble.',
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    material: 'Metal with pearls and beads',
    colors: ['Silver & Pearl'],
    care: 'Handle gently',
  },
  {
    id: 'key-010',
    name: 'Black Bow Star Keychain',
    category: 'keychains',
    price: 10707,
    image: `${SUPABASE_IMG}/phone-charm-black-white-strap.jpg`,
    description: 'Sophisticated black bow with star and pearl accents.',
    rating: 4.7,
    reviewCount: 128,
    inStock: true,
    material: 'Black metal with silver charms',
    colors: ['Black & Silver'],
    care: 'Avoid moisture',
  },
  {
    id: 'key-011',
    name: 'Pastel Charm Cascade Keychain',
    category: 'keychains',
    price: 10707,
    image: `${SUPABASE_IMG}/phone-charm-pink-beaded-strap.jpg`,
    description: 'Pastel beads with multiple charm strands.',
    rating: 4.6,
    reviewCount: 96,
    inStock: true,
    material: 'Pastel beads with metal charms',
    colors: ['Pastel Mix'],
    care: 'Keep clean',
  },
  {
    id: 'key-012',
    name: 'Turquoise Bow Charm Keychain',
    category: 'keychains',
    price: 10707,
    image: `${SUPABASE_IMG}/phone-charm-teal-flower-fairy.jpg`,
    description: 'Vibrant turquoise bow with pearl and star charms.',
    rating: 4.7,
    reviewCount: 121,
    inStock: true,
    material: 'Enamel with pearls',
    colors: ['Turquoise'],
    care: 'Wipe clean',
  },
  {
    id: 'brc-001',
    name: 'Charm Beaded Chain Bracelet',
    category: 'bracelets',
    price: 14037,
    image: `${SUPABASE_IMG}/bracelet-black-fairy-charm.jpg`,
    description: 'Classic chain bracelet with assorted charms and pearl beads.',
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    badge: 'trending',
    material: 'Silver-tone chain with beads',
    colors: ['Silver & Pearl'],
    dimensions: 'Adjustable 7-8 inches',
    care: 'Avoid chlorine',
  },
  {
    id: 'brc-002',
    name: 'Pearl & Heart Luxury Bracelet',
    category: 'bracelets',
    price: 13197,
    originalPrice: 24807,
    image: `${SUPABASE_IMG}/bracelet-white-rose-charm.jpg`,
    description: 'Premium pearl and rose charm bracelet for special occasions.',
    rating: 5.0,
    reviewCount: 245,
    inStock: true,
    badge: 'sale',
    material: 'Freshwater pearls with silver',
    colors: ['White Pearl'],
    dimensions: 'Adjustable 7-9 inches',
    care: 'Store in soft pouch',
  },
  {
    id: 'brc-003',
    name: 'Black Bead Statement Bracelet',
    category: 'bracelets',
    price: 14037,
    image: `${SUPABASE_IMG}/phone-charm-red-double-strand.jpg`,
    description: 'Bold red and black beads with mixed metal charms.',
    rating: 4.7,
    reviewCount: 108,
    inStock: true,
    material: 'Obsidian-style beads',
    colors: ['Red & Black'],
    dimensions: 'Fits 6-8 inches',
    care: 'Clean with soft brush',
  },
  {
    id: 'brc-004',
    name: 'Pastel Bow Beads Bracelet',
    category: 'bracelets',
    price: 15697,
    image: `${SUPABASE_IMG}/bracelets-red-pearl-bow.jpg`,
    description: 'Delicate red and pearl beads with pretty bow charm.',
    rating: 4.8,
    reviewCount: 178,
    inStock: true,
    badge: 'new',
    material: 'Acrylic beads with bow',
    colors: ['Red & Pearl'],
    dimensions: 'Adjustable 6-8 inches',
    care: 'Avoid prolonged moisture',
  },
  {
    id: 'nck-001',
    name: 'Bow & Heart Bead Necklace',
    category: 'necklaces',
    price: 16527,
    image: `${SUPABASE_IMG}/phone-charm-red-bow-heart.jpg`,
    description: 'Elegant bow with cascading heart and bead charm details.',
    rating: 4.8,
    reviewCount: 134,
    inStock: true,
    badge: 'trending',
    material: 'Metal bow with acrylic beads',
    colors: ['Red & White'],
    dimensions: '16-18 inches adjustable',
    care: 'Avoid water',
  },
  {
    id: 'nck-002',
    name: 'Pearl & Flower Necklace',
    category: 'necklaces',
    price: 17357,
    image: `${SUPABASE_IMG}/phone-charm-red-cake.jpg`,
    description: 'Double strand with pearls, flowers, and charm elements.',
    rating: 4.9,
    reviewCount: 189,
    inStock: true,
    material: 'Pearls, metal, and acrylic',
    colors: ['Pearl & Rose'],
    dimensions: '18-20 inches adjustable',
    care: 'Store separately',
  },
  {
    id: 'nck-003',
    name: 'Green Bow Cascade Necklace',
    category: 'necklaces',
    price: 16527,
    originalPrice: 24807,
    image: `${SUPABASE_IMG}/necklace-green-heart-locket.jpg`,
    description: 'Green and pearl heart locket necklace with bow detail.',
    rating: 4.7,
    reviewCount: 112,
    inStock: true,
    badge: 'sale',
    material: 'Enamel with pearls and beads',
    colors: ['Green & Pearl'],
    dimensions: '17-19 inches adjustable',
    care: 'Keep dry',
  },
  {
    id: 'nck-004',
    name: 'Heart Charm Pendant Necklace',
    category: 'necklaces',
    price: 16527,
    image: `${SUPABASE_IMG}/phone-charm-red-heart-triple.jpg`,
    description: 'Red heart charm with pearl and bead accents on cord.',
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    badge: 'new',
    material: 'Acrylic heart with cord',
    colors: ['Red & Pearl'],
    dimensions: '16-18 inches adjustable',
    care: 'Avoid excessive moisture',
  },
  ];

export function getProductsByCategory(category: Product['category']): Product[] {
  return products.filter((product) => product.category === category);
}

export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((product) => product.badge === 'trending' || product.badge === 'new').slice(0, 8);
}

export function getSaleProducts(): Product[] {
  return products.filter((product) => product.originalPrice);
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase();
  return products.filter((product) => product.name.toLowerCase().includes(lowerQuery) || product.description.toLowerCase().includes(lowerQuery) || (product.material?.toLowerCase().includes(lowerQuery) ?? false));
}

export const PRODUCT_STATS = {
  total: products.length,
  byCategory: {
    earrings: products.filter((p) => p.category === 'earrings').length,
    keychains: products.filter((p) => p.category === 'keychains').length,
    bracelets: products.filter((p) => p.category === 'bracelets').length,
    necklaces: products.filter((p) => p.category === 'necklaces').length,
  },
  averageRating: (products.reduce((sum, p) => sum + p.rating, 0) / products.length).toFixed(1),
  onSale: products.filter((p) => p.originalPrice).length,
};

export function formatINR(amount: number): string {
  return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(amount);
}

export function getProduct(id: string): Product | undefined {
  return getProductById(id);
}
